/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2019-11-26 06:36:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.Product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Product.ProductVO;
import java.util.ArrayList;

public final class Product_005fDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Product.ProductVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      Product.ProductDAO dao = null;
      dao = (Product.ProductDAO) _jspx_page_context.getAttribute("dao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (dao == null){
        dao = new Product.ProductDAO();
        _jspx_page_context.setAttribute("dao", dao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MY Shop</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../css/Product.css?after\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/product_detail.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar value = $(\"#amount option:selected\").val();\r\n");
      out.write("\t\tvar price = $(\"#price\").val();\r\n");
      out.write("\r\n");
      out.write("\t\tvar total = Number(price) * Number(value);\r\n");
      out.write("\t\ttotal = parseInt(total);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#total_money\").html(total);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#amount\").change(function() {\r\n");
      out.write("\t\t\tvar value = $(\"#amount option:selected\").val();\r\n");
      out.write("\t\t\tvar price = $(\"#price\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar total_price = Number(price) * Number(value);\r\n");
      out.write("\t\t\ttotal_price = parseInt(total_price);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#total_money\").html(total_price);\r\n");
      out.write("\t\t\t$(\"#total_money_value\").val(total_price);\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		String num = request.getParameter("num");
		dao.UpdateHit(num);
		ArrayList<ProductVO> list = dao.getProductDetail(num);
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Fix/Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<form action=\"../Cart/CartAdd.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				for (ProductVO vo : list) {
			
      out.write("\r\n");
      out.write("\t\t\t<div id=\"product_function\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"product_img\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img src=\"../../uploadFile/");
      out.print(vo.getProduct_img());
      out.write("\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"image\" value=\"");
      out.print(vo.getProduct_img());
      out.write("\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--end product_img-->\r\n");
      out.write("\t\t\t\t<div id=\"product_detail\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"2\">상품명\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2>");
      out.print(vo.getProduct_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(vo.getProduct_name());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"num\" value=\"");
      out.print(vo.getProduct_num());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>가격</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(vo.getPrice());
      out.write(" 택배 배송 (2500원)<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(vo.getPrice());
      out.write("\" id=\"price\" name=\"price\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>수량</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select name=\"amount\" id=\"amount\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for (int i = 1; i <= 10; i++) {
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>색상 선택</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select name=\"color\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(vo.getColor());
      out.write('"');
      out.write('>');
      out.print(vo.getColor());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> <input type=\"hidden\" value=\"");
      out.print(vo.getColor());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>size</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(vo.getSize());
      out.write(" <input type=\"hidden\" name=\"size\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(vo.getSize());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>총 상품 금액</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"total_money\"></span> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"tot_money\" id=\"total_money_value\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input type=\"submit\" value=\"장바구니\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" value=\"결제하기\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"location.href='../Pay/PayMain.jsp'\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--end product_detail-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--end product_function-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tabbar\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"tab\">\r\n");
      out.write("\t\t\t<div id=\"tab_label\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"tabs\" id=\"tab1\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t<label for=\"tab1\">상세정보</label> <input type=\"radio\" name=\"tabs\"\r\n");
      out.write("\t\t\t\t\tid=\"tab2\"> <label for=\"tab2\">리뷰(review)</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"tabs\" id=\"tab3\"> <label for=\"tab3\">문의</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content1\">\r\n");
      out.write("\t\t\t\t<div id=\"member_id_box\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../../uploadFile/");
      out.print(vo.getProduct_detail_img());
      out.write("\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content2\">\r\n");
      out.write("\t\t\t\t<div id=\"member_pwd_box\">\r\n");
      out.write("\t\t\t\t\t아이디 <input type=\"text\" placeholder=\"아이디를 입력하세요\" id=\"id\">\r\n");
      out.write("\t\t\t\t\t전화번호 <input type=\"text\" placeholder=\"전화번호를 입력하세요\" id=\"pwd_phone\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" onclick=\"pwd_check()\" value=\"다음 단계\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content3\">\r\n");
      out.write("\t\t\t\t<div id=\"result\">\r\n");
      out.write("\t\t\t\t\t");

						out.print("아이디는 test 입니다.");
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content4\">\r\n");
      out.write("\t\t\t\t<div id=\"result\">\r\n");
      out.write("\t\t\t\t\t");

						out.print("비밀번호는 test 입니다.");
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Fix/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
